global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: dispatch

replicaCount: 1

image:
  # Those values are set by Maven filtering
  # and will be replaced with a valid version number during the build process.
  registry: @docker.repo@
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8082
  targetPort: 8082
  nodePort: 30082

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

kafka:
  serviceFQDN: "dispatch-kafka.dispatch.svc.cluster.local"
  port: 9092
  clientPort: 29092

wiremock:
  enabled: true
  serviceFQDN: "dispatch-wiremock.dispatch.svc.cluster.local"
  port: 8088

ingress:
  enabled: false

# Section for overriding values in subcharts defined in the Chart.yaml
tracking:
  dispatch:
    enabled: false
  kafka:
    enabled: false
    serviceFQDN: "dispatch-kafka.dispatch.svc.cluster.local"
    advertisedListenersString: "PLAINTEXT://dispatch-kafka.dispatch.svc.cluster.local:9092,PLAINTEXT_HOST://dispatch-kafka.dispatch.svc.cluster.local:29092"