global:
  timezone: Europe/Zurich
  timezonePath: /etc/localtime
  springDebug: false
  namespace: dispatch

replicaCount: 1

image: # renovate:ignore
  repository: @docker.repo@/@project.artifactId@ # renovate:ignore
  tag: @project.version@ # renovate:ignore

bitnamiKafkaImage:
  repository: bitnami/kafka
  tag: "3.9.0"
  pullPolicy: IfNotPresent

busyboxImage:
  repository: busybox
  tag: "1.37.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8082
  targetPort: 8082
  nodePort: 30082

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

probes:
  startup:
    failureThreshold: 30
    periodSeconds: 10
  readiness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

kafka:
  serviceFQDN: "dispatch-kafka.dispatch.svc.cluster.local"
  port: 9092
  clientPort: 29092

wiremock:
  enabled: true
  serviceFQDN: "dispatch-wiremock.dispatch.svc.cluster.local"
  port: 8088

ingress:
  enabled: false

# Section for overriding values in subcharts defined in the Chart.yaml
tracking:
  dispatch:
    enabled: false
  kafka:
    enabled: false
    serviceFQDN: "dispatch-kafka.dispatch.svc.cluster.local"
    advertisedListenersString: "PLAINTEXT://dispatch-kafka.dispatch.svc.cluster.local:9092,PLAINTEXT_HOST://dispatch-kafka.dispatch.svc.cluster.local:29092"