spring:
  application:
    name: dispatch
    
  kafka:
    # See: https://docs.conduktor.io/desktop/kafka-cluster-connection/setting-up-a-connection-to-kafka/connecting-to-kafka-running-on-windows-wsl-2/#two-ways-to-fix-this
    # and: https://stackoverflow.com/questions/46158296/kafka-broker-not-available-at-starting
    bootstrap-servers: "[::1]:9092"
    
    admin:
      properties:
        bootstrap.servers: "[::1]:9092"
      auto-create: false
      
    consumer:
      # configs below are not taken anymore because we have the DispatchConfiguration class
      bootstrap-servers: "[::1]:9092"
      #value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: dev.lydtech.dispatch.message.OrderCreated
        spring.json.trusted.packages: "*"
        allow.auto.create.topics: false
  
  docker:
    compose:
      enabled: false
      stop:
        command: down  

management:
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
  endpoint:
    configprops:
      # WARNING: SECURITY RISK - DO NOT USE IN PRODUCTION ENVIRONMENT
      # This configuration exposes sensitive data and should only be used for development or testing purposes.
      # Ensure this is disabled in any environment where security is a concern.
      show-values: ALWAYS
    health:
      probes:
        enabled: true
      show-details: always

dispatch:
  stockServiceEndpoint: http://localhost:8888/api/stock
  
logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true
  format:
    style: http
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
  predicate:
    exclude:
      # Exclude HTML-related calls and specific endpoints that Logbook doesn't handle correctly
      - path: /actuator/health/**
      - path: /h2-console/**  # Exclude H2 console
      - path: /swagger-ui/**  # Exclude Swagger UI if used
      - path: /v3/api-docs/** # Exclude OpenAPI docs if used

        # Exclude HTML-related calls and web resources
      - path: /favicon.ico
      - path: /**/*.html
      - path: /**/*.css
      - path: /**/*.js
      - path: /**/*.png
      - path: /**/*.jpg
      - path: /**/*.jpeg
      - path: /**/*.gif
      - path: /**/*.ico
      - path: /**/favicon.ico
      - path: /**/webjars/**
        # Exclude other common web resources
      - path: /**/assets/**
      - path: /**/static/**
      - path: /**/public/**
      - path: /**/resources/**
      - path: /webjars/**
        # Add more exclusions as needed    
